### ISSUE TITLE
Authentication checklist

### ISSUE THREAD

**Issue by claflamme** [claflamme/broadsheet#1]
### Registration

- [x] Requires both email and password fields
- [x] Checks that email is valid
- [x] Checks that password is minimum 6 characters
- [x] Checks that password is maximum 72 **bytes** before processing (maximum input length for [bcryptjs](https://www.npmjs.com/package/bcryptjs) library)
- [x] Handles email already taken
- [x] Returns a `token` property on success
- [x] Stores the auth token in the DB

### Authentication

- [x] Requires both email and password fields
- [x] Checks that password is maximum 72 bytes before processing
- [x] Handles user not found
- [x] Handles incorrect password
- [x] Returns a `token` property on success
- [x] Stores the auth token in the DB
